################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/doom/am_map.c \
../Core/Src/doom/d_event.c \
../Core/Src/doom/d_items.c \
../Core/Src/doom/d_iwad.c \
../Core/Src/doom/d_loop.c \
../Core/Src/doom/d_main.c \
../Core/Src/doom/d_mode.c \
../Core/Src/doom/d_net.c \
../Core/Src/doom/deh_doom.c \
../Core/Src/doom/deh_str.c \
../Core/Src/doom/doom_icon.c \
../Core/Src/doom/doomdef.c \
../Core/Src/doom/doomstat.c \
../Core/Src/doom/dstrings.c \
../Core/Src/doom/f_finale.c \
../Core/Src/doom/f_wipe.c \
../Core/Src/doom/g_game.c \
../Core/Src/doom/gusconf.c \
../Core/Src/doom/hu_lib.c \
../Core/Src/doom/hu_stuff.c \
../Core/Src/doom/i_cdmus.c \
../Core/Src/doom/i_endoom.c \
../Core/Src/doom/i_flmusic.c \
../Core/Src/doom/i_glob.c \
../Core/Src/doom/i_input.c \
../Core/Src/doom/i_joystick.c \
../Core/Src/doom/i_main.c \
../Core/Src/doom/i_sound.c \
../Core/Src/doom/i_system.c \
../Core/Src/doom/i_timer.c \
../Core/Src/doom/i_video.c \
../Core/Src/doom/i_videohr.c \
../Core/Src/doom/i_winmusic.c \
../Core/Src/doom/info.c \
../Core/Src/doom/m_argv.c \
../Core/Src/doom/m_bbox.c \
../Core/Src/doom/m_cheat.c \
../Core/Src/doom/m_config.c \
../Core/Src/doom/m_controls.c \
../Core/Src/doom/m_fixed.c \
../Core/Src/doom/m_menu.c \
../Core/Src/doom/m_misc.c \
../Core/Src/doom/m_random.c \
../Core/Src/doom/memio.c \
../Core/Src/doom/midifallback.c \
../Core/Src/doom/midifile.c \
../Core/Src/doom/mus2mid.c \
../Core/Src/doom/net_client.c \
../Core/Src/doom/net_common.c \
../Core/Src/doom/net_dedicated.c \
../Core/Src/doom/net_gui.c \
../Core/Src/doom/net_io.c \
../Core/Src/doom/net_loop.c \
../Core/Src/doom/net_packet.c \
../Core/Src/doom/net_petname.c \
../Core/Src/doom/net_sdl.c \
../Core/Src/doom/net_server.c \
../Core/Src/doom/p_ceilng.c \
../Core/Src/doom/p_doors.c \
../Core/Src/doom/p_enemy.c \
../Core/Src/doom/p_floor.c \
../Core/Src/doom/p_inter.c \
../Core/Src/doom/p_lights.c \
../Core/Src/doom/p_map.c \
../Core/Src/doom/p_maputl.c \
../Core/Src/doom/p_mobj.c \
../Core/Src/doom/p_plats.c \
../Core/Src/doom/p_pspr.c \
../Core/Src/doom/p_saveg.c \
../Core/Src/doom/p_setup.c \
../Core/Src/doom/p_sight.c \
../Core/Src/doom/p_spec.c \
../Core/Src/doom/p_switch.c \
../Core/Src/doom/p_telept.c \
../Core/Src/doom/p_tick.c \
../Core/Src/doom/p_user.c \
../Core/Src/doom/r_bsp.c \
../Core/Src/doom/r_data.c \
../Core/Src/doom/r_draw.c \
../Core/Src/doom/r_main.c \
../Core/Src/doom/r_plane.c \
../Core/Src/doom/r_segs.c \
../Core/Src/doom/r_sky.c \
../Core/Src/doom/r_things.c \
../Core/Src/doom/s_sound.c \
../Core/Src/doom/sha1.c \
../Core/Src/doom/sounds.c \
../Core/Src/doom/st_lib.c \
../Core/Src/doom/st_stuff.c \
../Core/Src/doom/statdump.c \
../Core/Src/doom/tables.c \
../Core/Src/doom/v_diskicon.c \
../Core/Src/doom/v_video.c \
../Core/Src/doom/w_checksum.c \
../Core/Src/doom/w_file.c \
../Core/Src/doom/w_file_posix.c \
../Core/Src/doom/w_file_stdc.c \
../Core/Src/doom/w_file_win32.c \
../Core/Src/doom/w_main.c \
../Core/Src/doom/w_merge.c \
../Core/Src/doom/w_wad.c \
../Core/Src/doom/wi_stuff.c \
../Core/Src/doom/z_zone.c 

OBJS += \
./Core/Src/doom/am_map.o \
./Core/Src/doom/d_event.o \
./Core/Src/doom/d_items.o \
./Core/Src/doom/d_iwad.o \
./Core/Src/doom/d_loop.o \
./Core/Src/doom/d_main.o \
./Core/Src/doom/d_mode.o \
./Core/Src/doom/d_net.o \
./Core/Src/doom/deh_doom.o \
./Core/Src/doom/deh_str.o \
./Core/Src/doom/doom_icon.o \
./Core/Src/doom/doomdef.o \
./Core/Src/doom/doomstat.o \
./Core/Src/doom/dstrings.o \
./Core/Src/doom/f_finale.o \
./Core/Src/doom/f_wipe.o \
./Core/Src/doom/g_game.o \
./Core/Src/doom/gusconf.o \
./Core/Src/doom/hu_lib.o \
./Core/Src/doom/hu_stuff.o \
./Core/Src/doom/i_cdmus.o \
./Core/Src/doom/i_endoom.o \
./Core/Src/doom/i_flmusic.o \
./Core/Src/doom/i_glob.o \
./Core/Src/doom/i_input.o \
./Core/Src/doom/i_joystick.o \
./Core/Src/doom/i_main.o \
./Core/Src/doom/i_sound.o \
./Core/Src/doom/i_system.o \
./Core/Src/doom/i_timer.o \
./Core/Src/doom/i_video.o \
./Core/Src/doom/i_videohr.o \
./Core/Src/doom/i_winmusic.o \
./Core/Src/doom/info.o \
./Core/Src/doom/m_argv.o \
./Core/Src/doom/m_bbox.o \
./Core/Src/doom/m_cheat.o \
./Core/Src/doom/m_config.o \
./Core/Src/doom/m_controls.o \
./Core/Src/doom/m_fixed.o \
./Core/Src/doom/m_menu.o \
./Core/Src/doom/m_misc.o \
./Core/Src/doom/m_random.o \
./Core/Src/doom/memio.o \
./Core/Src/doom/midifallback.o \
./Core/Src/doom/midifile.o \
./Core/Src/doom/mus2mid.o \
./Core/Src/doom/net_client.o \
./Core/Src/doom/net_common.o \
./Core/Src/doom/net_dedicated.o \
./Core/Src/doom/net_gui.o \
./Core/Src/doom/net_io.o \
./Core/Src/doom/net_loop.o \
./Core/Src/doom/net_packet.o \
./Core/Src/doom/net_petname.o \
./Core/Src/doom/net_sdl.o \
./Core/Src/doom/net_server.o \
./Core/Src/doom/p_ceilng.o \
./Core/Src/doom/p_doors.o \
./Core/Src/doom/p_enemy.o \
./Core/Src/doom/p_floor.o \
./Core/Src/doom/p_inter.o \
./Core/Src/doom/p_lights.o \
./Core/Src/doom/p_map.o \
./Core/Src/doom/p_maputl.o \
./Core/Src/doom/p_mobj.o \
./Core/Src/doom/p_plats.o \
./Core/Src/doom/p_pspr.o \
./Core/Src/doom/p_saveg.o \
./Core/Src/doom/p_setup.o \
./Core/Src/doom/p_sight.o \
./Core/Src/doom/p_spec.o \
./Core/Src/doom/p_switch.o \
./Core/Src/doom/p_telept.o \
./Core/Src/doom/p_tick.o \
./Core/Src/doom/p_user.o \
./Core/Src/doom/r_bsp.o \
./Core/Src/doom/r_data.o \
./Core/Src/doom/r_draw.o \
./Core/Src/doom/r_main.o \
./Core/Src/doom/r_plane.o \
./Core/Src/doom/r_segs.o \
./Core/Src/doom/r_sky.o \
./Core/Src/doom/r_things.o \
./Core/Src/doom/s_sound.o \
./Core/Src/doom/sha1.o \
./Core/Src/doom/sounds.o \
./Core/Src/doom/st_lib.o \
./Core/Src/doom/st_stuff.o \
./Core/Src/doom/statdump.o \
./Core/Src/doom/tables.o \
./Core/Src/doom/v_diskicon.o \
./Core/Src/doom/v_video.o \
./Core/Src/doom/w_checksum.o \
./Core/Src/doom/w_file.o \
./Core/Src/doom/w_file_posix.o \
./Core/Src/doom/w_file_stdc.o \
./Core/Src/doom/w_file_win32.o \
./Core/Src/doom/w_main.o \
./Core/Src/doom/w_merge.o \
./Core/Src/doom/w_wad.o \
./Core/Src/doom/wi_stuff.o \
./Core/Src/doom/z_zone.o 

C_DEPS += \
./Core/Src/doom/am_map.d \
./Core/Src/doom/d_event.d \
./Core/Src/doom/d_items.d \
./Core/Src/doom/d_iwad.d \
./Core/Src/doom/d_loop.d \
./Core/Src/doom/d_main.d \
./Core/Src/doom/d_mode.d \
./Core/Src/doom/d_net.d \
./Core/Src/doom/deh_doom.d \
./Core/Src/doom/deh_str.d \
./Core/Src/doom/doom_icon.d \
./Core/Src/doom/doomdef.d \
./Core/Src/doom/doomstat.d \
./Core/Src/doom/dstrings.d \
./Core/Src/doom/f_finale.d \
./Core/Src/doom/f_wipe.d \
./Core/Src/doom/g_game.d \
./Core/Src/doom/gusconf.d \
./Core/Src/doom/hu_lib.d \
./Core/Src/doom/hu_stuff.d \
./Core/Src/doom/i_cdmus.d \
./Core/Src/doom/i_endoom.d \
./Core/Src/doom/i_flmusic.d \
./Core/Src/doom/i_glob.d \
./Core/Src/doom/i_input.d \
./Core/Src/doom/i_joystick.d \
./Core/Src/doom/i_main.d \
./Core/Src/doom/i_sound.d \
./Core/Src/doom/i_system.d \
./Core/Src/doom/i_timer.d \
./Core/Src/doom/i_video.d \
./Core/Src/doom/i_videohr.d \
./Core/Src/doom/i_winmusic.d \
./Core/Src/doom/info.d \
./Core/Src/doom/m_argv.d \
./Core/Src/doom/m_bbox.d \
./Core/Src/doom/m_cheat.d \
./Core/Src/doom/m_config.d \
./Core/Src/doom/m_controls.d \
./Core/Src/doom/m_fixed.d \
./Core/Src/doom/m_menu.d \
./Core/Src/doom/m_misc.d \
./Core/Src/doom/m_random.d \
./Core/Src/doom/memio.d \
./Core/Src/doom/midifallback.d \
./Core/Src/doom/midifile.d \
./Core/Src/doom/mus2mid.d \
./Core/Src/doom/net_client.d \
./Core/Src/doom/net_common.d \
./Core/Src/doom/net_dedicated.d \
./Core/Src/doom/net_gui.d \
./Core/Src/doom/net_io.d \
./Core/Src/doom/net_loop.d \
./Core/Src/doom/net_packet.d \
./Core/Src/doom/net_petname.d \
./Core/Src/doom/net_sdl.d \
./Core/Src/doom/net_server.d \
./Core/Src/doom/p_ceilng.d \
./Core/Src/doom/p_doors.d \
./Core/Src/doom/p_enemy.d \
./Core/Src/doom/p_floor.d \
./Core/Src/doom/p_inter.d \
./Core/Src/doom/p_lights.d \
./Core/Src/doom/p_map.d \
./Core/Src/doom/p_maputl.d \
./Core/Src/doom/p_mobj.d \
./Core/Src/doom/p_plats.d \
./Core/Src/doom/p_pspr.d \
./Core/Src/doom/p_saveg.d \
./Core/Src/doom/p_setup.d \
./Core/Src/doom/p_sight.d \
./Core/Src/doom/p_spec.d \
./Core/Src/doom/p_switch.d \
./Core/Src/doom/p_telept.d \
./Core/Src/doom/p_tick.d \
./Core/Src/doom/p_user.d \
./Core/Src/doom/r_bsp.d \
./Core/Src/doom/r_data.d \
./Core/Src/doom/r_draw.d \
./Core/Src/doom/r_main.d \
./Core/Src/doom/r_plane.d \
./Core/Src/doom/r_segs.d \
./Core/Src/doom/r_sky.d \
./Core/Src/doom/r_things.d \
./Core/Src/doom/s_sound.d \
./Core/Src/doom/sha1.d \
./Core/Src/doom/sounds.d \
./Core/Src/doom/st_lib.d \
./Core/Src/doom/st_stuff.d \
./Core/Src/doom/statdump.d \
./Core/Src/doom/tables.d \
./Core/Src/doom/v_diskicon.d \
./Core/Src/doom/v_video.d \
./Core/Src/doom/w_checksum.d \
./Core/Src/doom/w_file.d \
./Core/Src/doom/w_file_posix.d \
./Core/Src/doom/w_file_stdc.d \
./Core/Src/doom/w_file_win32.d \
./Core/Src/doom/w_main.d \
./Core/Src/doom/w_merge.d \
./Core/Src/doom/w_wad.d \
./Core/Src/doom/wi_stuff.d \
./Core/Src/doom/z_zone.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/doom/%.o Core/Src/doom/%.su Core/Src/doom/%.cyclo: ../Core/Src/doom/%.c Core/Src/doom/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -DUSE_PWR_LDO_SUPPLY -DUSE_HAL_DRIVER -DSTM32H743xx -c -I../Core/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc -I../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../Drivers/CMSIS/Include -I../FATFS/Target -I../FATFS/App -I../Middlewares/Third_Party/FatFs/src -I"/home/tatu/STM32CubeIDE/workspace_1.17.0/stm32_h743_doom_port/Core" -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Core-2f-Src-2f-doom

clean-Core-2f-Src-2f-doom:
	-$(RM) ./Core/Src/doom/am_map.cyclo ./Core/Src/doom/am_map.d ./Core/Src/doom/am_map.o ./Core/Src/doom/am_map.su ./Core/Src/doom/d_event.cyclo ./Core/Src/doom/d_event.d ./Core/Src/doom/d_event.o ./Core/Src/doom/d_event.su ./Core/Src/doom/d_items.cyclo ./Core/Src/doom/d_items.d ./Core/Src/doom/d_items.o ./Core/Src/doom/d_items.su ./Core/Src/doom/d_iwad.cyclo ./Core/Src/doom/d_iwad.d ./Core/Src/doom/d_iwad.o ./Core/Src/doom/d_iwad.su ./Core/Src/doom/d_loop.cyclo ./Core/Src/doom/d_loop.d ./Core/Src/doom/d_loop.o ./Core/Src/doom/d_loop.su ./Core/Src/doom/d_main.cyclo ./Core/Src/doom/d_main.d ./Core/Src/doom/d_main.o ./Core/Src/doom/d_main.su ./Core/Src/doom/d_mode.cyclo ./Core/Src/doom/d_mode.d ./Core/Src/doom/d_mode.o ./Core/Src/doom/d_mode.su ./Core/Src/doom/d_net.cyclo ./Core/Src/doom/d_net.d ./Core/Src/doom/d_net.o ./Core/Src/doom/d_net.su ./Core/Src/doom/deh_doom.cyclo ./Core/Src/doom/deh_doom.d ./Core/Src/doom/deh_doom.o ./Core/Src/doom/deh_doom.su ./Core/Src/doom/deh_str.cyclo ./Core/Src/doom/deh_str.d ./Core/Src/doom/deh_str.o ./Core/Src/doom/deh_str.su ./Core/Src/doom/doom_icon.cyclo ./Core/Src/doom/doom_icon.d ./Core/Src/doom/doom_icon.o ./Core/Src/doom/doom_icon.su ./Core/Src/doom/doomdef.cyclo ./Core/Src/doom/doomdef.d ./Core/Src/doom/doomdef.o ./Core/Src/doom/doomdef.su ./Core/Src/doom/doomstat.cyclo ./Core/Src/doom/doomstat.d ./Core/Src/doom/doomstat.o ./Core/Src/doom/doomstat.su ./Core/Src/doom/dstrings.cyclo ./Core/Src/doom/dstrings.d ./Core/Src/doom/dstrings.o ./Core/Src/doom/dstrings.su ./Core/Src/doom/f_finale.cyclo ./Core/Src/doom/f_finale.d ./Core/Src/doom/f_finale.o ./Core/Src/doom/f_finale.su ./Core/Src/doom/f_wipe.cyclo ./Core/Src/doom/f_wipe.d ./Core/Src/doom/f_wipe.o ./Core/Src/doom/f_wipe.su ./Core/Src/doom/g_game.cyclo ./Core/Src/doom/g_game.d ./Core/Src/doom/g_game.o ./Core/Src/doom/g_game.su ./Core/Src/doom/gusconf.cyclo ./Core/Src/doom/gusconf.d ./Core/Src/doom/gusconf.o ./Core/Src/doom/gusconf.su ./Core/Src/doom/hu_lib.cyclo ./Core/Src/doom/hu_lib.d ./Core/Src/doom/hu_lib.o ./Core/Src/doom/hu_lib.su ./Core/Src/doom/hu_stuff.cyclo ./Core/Src/doom/hu_stuff.d ./Core/Src/doom/hu_stuff.o ./Core/Src/doom/hu_stuff.su ./Core/Src/doom/i_cdmus.cyclo ./Core/Src/doom/i_cdmus.d ./Core/Src/doom/i_cdmus.o ./Core/Src/doom/i_cdmus.su ./Core/Src/doom/i_endoom.cyclo ./Core/Src/doom/i_endoom.d ./Core/Src/doom/i_endoom.o ./Core/Src/doom/i_endoom.su ./Core/Src/doom/i_flmusic.cyclo ./Core/Src/doom/i_flmusic.d ./Core/Src/doom/i_flmusic.o ./Core/Src/doom/i_flmusic.su ./Core/Src/doom/i_glob.cyclo ./Core/Src/doom/i_glob.d ./Core/Src/doom/i_glob.o ./Core/Src/doom/i_glob.su ./Core/Src/doom/i_input.cyclo ./Core/Src/doom/i_input.d ./Core/Src/doom/i_input.o ./Core/Src/doom/i_input.su ./Core/Src/doom/i_joystick.cyclo ./Core/Src/doom/i_joystick.d ./Core/Src/doom/i_joystick.o ./Core/Src/doom/i_joystick.su ./Core/Src/doom/i_main.cyclo ./Core/Src/doom/i_main.d ./Core/Src/doom/i_main.o ./Core/Src/doom/i_main.su ./Core/Src/doom/i_sound.cyclo ./Core/Src/doom/i_sound.d ./Core/Src/doom/i_sound.o ./Core/Src/doom/i_sound.su ./Core/Src/doom/i_system.cyclo ./Core/Src/doom/i_system.d ./Core/Src/doom/i_system.o ./Core/Src/doom/i_system.su ./Core/Src/doom/i_timer.cyclo ./Core/Src/doom/i_timer.d ./Core/Src/doom/i_timer.o ./Core/Src/doom/i_timer.su ./Core/Src/doom/i_video.cyclo ./Core/Src/doom/i_video.d ./Core/Src/doom/i_video.o ./Core/Src/doom/i_video.su ./Core/Src/doom/i_videohr.cyclo ./Core/Src/doom/i_videohr.d ./Core/Src/doom/i_videohr.o ./Core/Src/doom/i_videohr.su ./Core/Src/doom/i_winmusic.cyclo ./Core/Src/doom/i_winmusic.d ./Core/Src/doom/i_winmusic.o ./Core/Src/doom/i_winmusic.su ./Core/Src/doom/info.cyclo ./Core/Src/doom/info.d ./Core/Src/doom/info.o ./Core/Src/doom/info.su ./Core/Src/doom/m_argv.cyclo ./Core/Src/doom/m_argv.d ./Core/Src/doom/m_argv.o ./Core/Src/doom/m_argv.su ./Core/Src/doom/m_bbox.cyclo ./Core/Src/doom/m_bbox.d ./Core/Src/doom/m_bbox.o ./Core/Src/doom/m_bbox.su ./Core/Src/doom/m_cheat.cyclo ./Core/Src/doom/m_cheat.d ./Core/Src/doom/m_cheat.o ./Core/Src/doom/m_cheat.su ./Core/Src/doom/m_config.cyclo ./Core/Src/doom/m_config.d ./Core/Src/doom/m_config.o ./Core/Src/doom/m_config.su ./Core/Src/doom/m_controls.cyclo ./Core/Src/doom/m_controls.d ./Core/Src/doom/m_controls.o ./Core/Src/doom/m_controls.su ./Core/Src/doom/m_fixed.cyclo ./Core/Src/doom/m_fixed.d ./Core/Src/doom/m_fixed.o ./Core/Src/doom/m_fixed.su ./Core/Src/doom/m_menu.cyclo ./Core/Src/doom/m_menu.d ./Core/Src/doom/m_menu.o ./Core/Src/doom/m_menu.su ./Core/Src/doom/m_misc.cyclo ./Core/Src/doom/m_misc.d ./Core/Src/doom/m_misc.o ./Core/Src/doom/m_misc.su ./Core/Src/doom/m_random.cyclo ./Core/Src/doom/m_random.d ./Core/Src/doom/m_random.o ./Core/Src/doom/m_random.su ./Core/Src/doom/memio.cyclo ./Core/Src/doom/memio.d ./Core/Src/doom/memio.o ./Core/Src/doom/memio.su ./Core/Src/doom/midifallback.cyclo ./Core/Src/doom/midifallback.d ./Core/Src/doom/midifallback.o ./Core/Src/doom/midifallback.su ./Core/Src/doom/midifile.cyclo ./Core/Src/doom/midifile.d ./Core/Src/doom/midifile.o ./Core/Src/doom/midifile.su ./Core/Src/doom/mus2mid.cyclo ./Core/Src/doom/mus2mid.d ./Core/Src/doom/mus2mid.o ./Core/Src/doom/mus2mid.su ./Core/Src/doom/net_client.cyclo ./Core/Src/doom/net_client.d ./Core/Src/doom/net_client.o ./Core/Src/doom/net_client.su ./Core/Src/doom/net_common.cyclo ./Core/Src/doom/net_common.d ./Core/Src/doom/net_common.o ./Core/Src/doom/net_common.su ./Core/Src/doom/net_dedicated.cyclo ./Core/Src/doom/net_dedicated.d ./Core/Src/doom/net_dedicated.o ./Core/Src/doom/net_dedicated.su ./Core/Src/doom/net_gui.cyclo ./Core/Src/doom/net_gui.d ./Core/Src/doom/net_gui.o ./Core/Src/doom/net_gui.su ./Core/Src/doom/net_io.cyclo ./Core/Src/doom/net_io.d ./Core/Src/doom/net_io.o ./Core/Src/doom/net_io.su ./Core/Src/doom/net_loop.cyclo ./Core/Src/doom/net_loop.d ./Core/Src/doom/net_loop.o ./Core/Src/doom/net_loop.su ./Core/Src/doom/net_packet.cyclo ./Core/Src/doom/net_packet.d ./Core/Src/doom/net_packet.o ./Core/Src/doom/net_packet.su
	-$(RM) ./Core/Src/doom/net_petname.cyclo ./Core/Src/doom/net_petname.d ./Core/Src/doom/net_petname.o ./Core/Src/doom/net_petname.su ./Core/Src/doom/net_sdl.cyclo ./Core/Src/doom/net_sdl.d ./Core/Src/doom/net_sdl.o ./Core/Src/doom/net_sdl.su ./Core/Src/doom/net_server.cyclo ./Core/Src/doom/net_server.d ./Core/Src/doom/net_server.o ./Core/Src/doom/net_server.su ./Core/Src/doom/p_ceilng.cyclo ./Core/Src/doom/p_ceilng.d ./Core/Src/doom/p_ceilng.o ./Core/Src/doom/p_ceilng.su ./Core/Src/doom/p_doors.cyclo ./Core/Src/doom/p_doors.d ./Core/Src/doom/p_doors.o ./Core/Src/doom/p_doors.su ./Core/Src/doom/p_enemy.cyclo ./Core/Src/doom/p_enemy.d ./Core/Src/doom/p_enemy.o ./Core/Src/doom/p_enemy.su ./Core/Src/doom/p_floor.cyclo ./Core/Src/doom/p_floor.d ./Core/Src/doom/p_floor.o ./Core/Src/doom/p_floor.su ./Core/Src/doom/p_inter.cyclo ./Core/Src/doom/p_inter.d ./Core/Src/doom/p_inter.o ./Core/Src/doom/p_inter.su ./Core/Src/doom/p_lights.cyclo ./Core/Src/doom/p_lights.d ./Core/Src/doom/p_lights.o ./Core/Src/doom/p_lights.su ./Core/Src/doom/p_map.cyclo ./Core/Src/doom/p_map.d ./Core/Src/doom/p_map.o ./Core/Src/doom/p_map.su ./Core/Src/doom/p_maputl.cyclo ./Core/Src/doom/p_maputl.d ./Core/Src/doom/p_maputl.o ./Core/Src/doom/p_maputl.su ./Core/Src/doom/p_mobj.cyclo ./Core/Src/doom/p_mobj.d ./Core/Src/doom/p_mobj.o ./Core/Src/doom/p_mobj.su ./Core/Src/doom/p_plats.cyclo ./Core/Src/doom/p_plats.d ./Core/Src/doom/p_plats.o ./Core/Src/doom/p_plats.su ./Core/Src/doom/p_pspr.cyclo ./Core/Src/doom/p_pspr.d ./Core/Src/doom/p_pspr.o ./Core/Src/doom/p_pspr.su ./Core/Src/doom/p_saveg.cyclo ./Core/Src/doom/p_saveg.d ./Core/Src/doom/p_saveg.o ./Core/Src/doom/p_saveg.su ./Core/Src/doom/p_setup.cyclo ./Core/Src/doom/p_setup.d ./Core/Src/doom/p_setup.o ./Core/Src/doom/p_setup.su ./Core/Src/doom/p_sight.cyclo ./Core/Src/doom/p_sight.d ./Core/Src/doom/p_sight.o ./Core/Src/doom/p_sight.su ./Core/Src/doom/p_spec.cyclo ./Core/Src/doom/p_spec.d ./Core/Src/doom/p_spec.o ./Core/Src/doom/p_spec.su ./Core/Src/doom/p_switch.cyclo ./Core/Src/doom/p_switch.d ./Core/Src/doom/p_switch.o ./Core/Src/doom/p_switch.su ./Core/Src/doom/p_telept.cyclo ./Core/Src/doom/p_telept.d ./Core/Src/doom/p_telept.o ./Core/Src/doom/p_telept.su ./Core/Src/doom/p_tick.cyclo ./Core/Src/doom/p_tick.d ./Core/Src/doom/p_tick.o ./Core/Src/doom/p_tick.su ./Core/Src/doom/p_user.cyclo ./Core/Src/doom/p_user.d ./Core/Src/doom/p_user.o ./Core/Src/doom/p_user.su ./Core/Src/doom/r_bsp.cyclo ./Core/Src/doom/r_bsp.d ./Core/Src/doom/r_bsp.o ./Core/Src/doom/r_bsp.su ./Core/Src/doom/r_data.cyclo ./Core/Src/doom/r_data.d ./Core/Src/doom/r_data.o ./Core/Src/doom/r_data.su ./Core/Src/doom/r_draw.cyclo ./Core/Src/doom/r_draw.d ./Core/Src/doom/r_draw.o ./Core/Src/doom/r_draw.su ./Core/Src/doom/r_main.cyclo ./Core/Src/doom/r_main.d ./Core/Src/doom/r_main.o ./Core/Src/doom/r_main.su ./Core/Src/doom/r_plane.cyclo ./Core/Src/doom/r_plane.d ./Core/Src/doom/r_plane.o ./Core/Src/doom/r_plane.su ./Core/Src/doom/r_segs.cyclo ./Core/Src/doom/r_segs.d ./Core/Src/doom/r_segs.o ./Core/Src/doom/r_segs.su ./Core/Src/doom/r_sky.cyclo ./Core/Src/doom/r_sky.d ./Core/Src/doom/r_sky.o ./Core/Src/doom/r_sky.su ./Core/Src/doom/r_things.cyclo ./Core/Src/doom/r_things.d ./Core/Src/doom/r_things.o ./Core/Src/doom/r_things.su ./Core/Src/doom/s_sound.cyclo ./Core/Src/doom/s_sound.d ./Core/Src/doom/s_sound.o ./Core/Src/doom/s_sound.su ./Core/Src/doom/sha1.cyclo ./Core/Src/doom/sha1.d ./Core/Src/doom/sha1.o ./Core/Src/doom/sha1.su ./Core/Src/doom/sounds.cyclo ./Core/Src/doom/sounds.d ./Core/Src/doom/sounds.o ./Core/Src/doom/sounds.su ./Core/Src/doom/st_lib.cyclo ./Core/Src/doom/st_lib.d ./Core/Src/doom/st_lib.o ./Core/Src/doom/st_lib.su ./Core/Src/doom/st_stuff.cyclo ./Core/Src/doom/st_stuff.d ./Core/Src/doom/st_stuff.o ./Core/Src/doom/st_stuff.su ./Core/Src/doom/statdump.cyclo ./Core/Src/doom/statdump.d ./Core/Src/doom/statdump.o ./Core/Src/doom/statdump.su ./Core/Src/doom/tables.cyclo ./Core/Src/doom/tables.d ./Core/Src/doom/tables.o ./Core/Src/doom/tables.su ./Core/Src/doom/v_diskicon.cyclo ./Core/Src/doom/v_diskicon.d ./Core/Src/doom/v_diskicon.o ./Core/Src/doom/v_diskicon.su ./Core/Src/doom/v_video.cyclo ./Core/Src/doom/v_video.d ./Core/Src/doom/v_video.o ./Core/Src/doom/v_video.su ./Core/Src/doom/w_checksum.cyclo ./Core/Src/doom/w_checksum.d ./Core/Src/doom/w_checksum.o ./Core/Src/doom/w_checksum.su ./Core/Src/doom/w_file.cyclo ./Core/Src/doom/w_file.d ./Core/Src/doom/w_file.o ./Core/Src/doom/w_file.su ./Core/Src/doom/w_file_posix.cyclo ./Core/Src/doom/w_file_posix.d ./Core/Src/doom/w_file_posix.o ./Core/Src/doom/w_file_posix.su ./Core/Src/doom/w_file_stdc.cyclo ./Core/Src/doom/w_file_stdc.d ./Core/Src/doom/w_file_stdc.o ./Core/Src/doom/w_file_stdc.su ./Core/Src/doom/w_file_win32.cyclo ./Core/Src/doom/w_file_win32.d ./Core/Src/doom/w_file_win32.o ./Core/Src/doom/w_file_win32.su ./Core/Src/doom/w_main.cyclo ./Core/Src/doom/w_main.d ./Core/Src/doom/w_main.o ./Core/Src/doom/w_main.su ./Core/Src/doom/w_merge.cyclo ./Core/Src/doom/w_merge.d ./Core/Src/doom/w_merge.o ./Core/Src/doom/w_merge.su ./Core/Src/doom/w_wad.cyclo ./Core/Src/doom/w_wad.d ./Core/Src/doom/w_wad.o ./Core/Src/doom/w_wad.su ./Core/Src/doom/wi_stuff.cyclo ./Core/Src/doom/wi_stuff.d ./Core/Src/doom/wi_stuff.o ./Core/Src/doom/wi_stuff.su ./Core/Src/doom/z_zone.cyclo ./Core/Src/doom/z_zone.d ./Core/Src/doom/z_zone.o ./Core/Src/doom/z_zone.su

.PHONY: clean-Core-2f-Src-2f-doom

